### ISSUE TITLE
It didn't work in pages/*.vue. How can I let it work?

### ISSUE THREAD

**Issue by MoeCasts** [anteriovieira/nuxt-sass-resources-loader#12]
I want it work in pages/*.vue. How can I make it?

**Comment by MoeCasts** [comment]
@anteriovieira The requirement is that I want to use the scss variables in pages/*.vue. However, the normal config can't meet my requirement.

**Comment by anteriovieira** [comment]
As you can see in our [test example](https://github.com/anteriovieira/nuxt-sass-resources-loader/blob/master/test/fixture/pages/index.vue) this works as you would like.

**Comment by MoeCasts** [comment]
Thank you very much. It's my mistake. I had forgot to add lang attr in style.

**Comment by anteriovieira** [comment]
Do not worry :smile:
