### ISSUE TITLE
Trouble getting it working

### ISSUE THREAD

**Issue by erichodges** [anteriovieira/nuxt-sass-resources-loader#15]
### Overview of the problem

- **Nodejs** version: 10.1.0
- **Nuxtjs** version: 1.0.0
- **nuxt-sass-resources-loader** version: 2.0.0

### Description
I want to have multiple sass files in /assets/scss and import them into /scss/main.scss. I've tried every configuration I could find for modules in nuxt.config.js. Here is the latest:

```
modules: [
    // provide path to the file with resources
    'nuxt-sass-resources-loader',
  ],
  sassResources: [
       '@/assets/scss/main.scss',
       '@/assets/scss/base.scss'
      
  ],
```
I'm getting an error that shows that variables in my base.scss file are not showing up in main.scss.
I don't understand what I'm doing wrong. 

my project is at:
https://github.com/erichodges/nuxt-bulma-boilerplate

**Comment by anteriovieira** [comment]
Hi @erichodges , please try version v2.0.2

**Comment by scottgearyau** [comment]
Hey @erichodges 

You config here is wrong:
`'@/assets/scss/base.scss'`

Should point to:
`'@/assets/scss/_base.scss'`

Assuming you copied straight from the SCSS file when switching over :)

**Comment by erichodges** [comment]
Thanks Scott,

One of the things I tried was switching between using the underscore and
not using it.  The new version, 2.0.2 fixed the issue.
