### ISSUE TITLE
Module build failed: Make sure 'options.resources' is String or Array of Strings.

### ISSUE THREAD

**Issue by dutchwebworks** [anteriovieira/nuxt-sass-resources-loader#17]
### Overview of the problem

- **Nodejs** version: 10.3
- **Nuxtjs** version: 1.4
- **nuxt-sass-resources-loader** version: 2.0.2

### Description

Getting an error while launching `npm run dev`. See below.

### Steps to reproduce

1. I installed 'nuxt-sass-resources-loader'
2. Updated my nuxt-config.js like https://github.com/dutchwebworks/nuxt-learning/blob/feature/nuxt-sass-resources-loader/nuxt.config.js
3. Removed all the old CSS @imports from all my Scss files. In favour of this solution.

### Expected behavior

To have global Scss vars., mixins and functions to work without importing those into every single Vue Nuxt component, page or layout.

I've tried configs like https://github.com/anteriovieira/nuxt-sass-resources-loader#usage but with no luck. See my temp. branch on https://github.com/dutchwebworks/nuxt-learning/blob/feature/nuxt-sass-resources-loader

### Actual behavior

```bash
Module build failed: Error:
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.

    at Object.module.exports (/Users/myname/Sites/nuxt-learning/node_modules/sass-resources-loader/lib/loader.js:73:18)
```

And now the whole Nuxt localhost:3000 doesn't give any response / is not working.

**Comment by Feelthewind** [comment]
+1

**Comment by Silverman42** [comment]
I actually have the same problem. When i build my nuxt app on local server (using either `npm run generate` or `npm run dev`) it builds successfully but when i try to run the build on travis CI so as to generate the static webpage. Here is the abridged form of the error from Travis CI log ->
```
> nuxt-template@1.0.0 generate /home/travis/build/Silverman42/newDSIHUB
> nuxt generate

2018-08-26T23:13:02.751Z nuxt:generate Generating...
2018-08-26T23:13:02.763Z nuxt:build App root: /home/travis/build/Silverman42/newDSIHUB
2018-08-26T23:13:02.764Z nuxt:build Generating /home/travis/build/Silverman42/newDSIHUB/.nuxt files...
2018-08-26T23:13:02.768Z nuxt:build Generating files...
2018-08-26T23:13:02.777Z nuxt:build Generating routes...
2018-08-26T23:13:02.797Z nuxt:build Building files...
 ERROR  Failed to compile with 15 errors23:13:18

 error  in ./layouts/custom.vue

Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/home/travis/build/Silverman42/newDSIHUB/node_modules/sass-resources-loader/lib/loader.js:73:18)

 @ ./node_modules/vue-style-loader?{"sourceMap":false}!./node_modules/css-loader?{"sourceMap":false,"minimize":true,"importLoaders":1,"alias":{"/assets":"/home/travis/build/Silverman42/newDSIHUB/assets","/static":"/home/travis/build/Silverman42/newDSIHUB/static"}}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4f1f7f45","scoped":true,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/sass-resources-loader/lib/loader.js?{"resources":["/home/travis/build/Silverman42/newDSIHUB/assets/scss/main.scss"]}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./layouts/custom.vue 4:14-677
 @ ./layouts/custom.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
```
 [Here](https://github.com/Silverman42/newDSIHUB) is a link to my repository

**Comment by thomasaull** [comment]
Did any of you managed to solve this? Having the same problem…

**Comment by dutchwebworks** [comment]
I fixed in on my demo project: [Nuxt learning](https://github.com/dutchwebworks/nuxt-learning)  on Github. 

Here's what I did ([merge commit](https://github.com/dutchwebworks/nuxt-learning/commit/e077aa016b06d9040cdd15d025511463fd863e4a)) in my demo project [Nuxt Learning - Dutchwebworks](https://nuxt-learning.herokuapp.com/) to have **global** `*.scss` **variables** (or other **helper files**, that don't generate any CSS!) be injected into every Nuxt / Vue component (or page).

### 1) Install this `nuxt-sass-resources-loader` Webpack loader:

```bash
npm i nuxt-sass-resources-loader
```

This will add it to the `package.json` files `dependencies` section.

### 2) Then in `nuxt.config.js` add the `nuxt-sass-resources-loader` array part to the (already present) `modules` section. 

```javascript
  modules: [
    ['nuxt-sass-resources-loader', [
      '@/assets/scss/helpers/_config.scss',
      '@/assets/scss/helpers/_flexbox.scss',
      '@/assets/scss/helpers/_grid.scss',
      '@/assets/scss/helpers/_respond-to.scss'
    ]]
  ],
```

Change your paths accordingly.

### 3) **Now REMOVE the Scss** `@import` rules **from every** `*.vue` file's `<style>` section.

```scss
<style lang="scss">
	@import "~/assets/scss/helpers.scss";

	.header {
		margin: 0 $body-margin;		
	}
</style>
```

Above `@import "~/assets/scss/helpers.scss";` (which was importing all the other `*.scss` helper files) is **no longer required**. This is now handled by Nuxt modules `nuxt-sass-resources-loader`.

### 4) Restart your local Nuxt dev project

Optionally quit running terminal with `ctrl + c`, then:

```bash
npm run dev
```

**Comment by dutchwebworks** [comment]
By the way: I also got a similar **global Scss variables** working on my **non-Nuxt** [Vue learning](https://github.com/dutchwebworks/vue-learning) (on Github) demo project called [Vue learning](https://vue-learning.dutchwebworks.nl/) which uses the `vue-cli` v3.x.

### 1) Check my project's `package.json` file

If you're missing any `sass-loader` and or `node-sass` `devDependencies`. Install them if required. Most of the Scss compiler stuff is asked when `vue create` (using `vue-cli` 3) your project.

### 2) In the `vue.config.js` use the Css `loaderOptions` section below:

```javascript
module.exports = {
    outputDir: "docs",
    css: {
        loaderOptions: {
            sass: {
                data: `
                    @import "@/scss/helpers/_config.scss";
                    @import "@/scss/helpers/_flexbox.scss";
                    @import "@/scss/helpers/_grid.scss";
                    @import "@/scss/helpers/_respond-to.scss";
                `
            }
        }
    }
}
```

This `loaderOptions` Sass `data` 'string' (back ticks) is inserted (prefixed) by Webpack into every `*.vue` file's `<style>` section.

**Comment by thomasaull** [comment]
Thanks, I appreciate your answers – but what you're telling me is basically the stuff I can find in the documentation, which didn't help me to solve my problem.

What did help though, was this line in the Readme: `Note that installing as a dev dependency --save-dev or -D will not work correctly.`

Also it only works with this configuration method for me:
```
modules: ['nuxt-sass-resources-loader'],
sassResources: ['@/assets/scss/constants.scss'],
```

which is weird, but since it's working I'm not complaining 🤷‍♂️

**Comment by anteriovieira** [comment]
@dutchwebworks thank you for sharing your solution with us.

@thomasaull I'm already working on the correction; Thank you for notifying the problem;

**Comment by david-mark** [comment]
Getting this in a Nuxt project every time. Doesn't matter whether the "sassResources" option is used or if the "resources" are pushed in an array. BTW, which is preferred at this time?

 Module build failed: Error:
[1]       Something wrong with provided resources.
[1]       Make sure 'options.resources' is String or Array of Strings.

The thing is obviously confused and unable to express the cause of its confusion.

EDIT: 

Never did fix that misleading error message? Apparently a bad path will cause it:

https://github.com/shakacode/sass-resources-loader/issues/12#issuecomment-318850009

**Comment by dutchwebworks** [comment]
Like mentioned in the [README.md](https://github.com/anteriovieira/nuxt-sass-resources-loader) of https://github.com/anteriovieira/nuxt-sass-resources-loader, please use the official community package [@nuxtjs/style-resources](https://github.com/nuxt-community/style-resources-module).

1) In short my setup (this is also in above [@nuxtjs/style-resources](https://github.com/nuxt-community/style-resources-module) documentation)

```bash
npm i sass-loader node-sass @nuxtjs/style-resources
```

2) Add `@nuxtjs/style-resources` module to the `modules`- section of your `nuxt.config.js`:

```bash
export default {
    modules: [
        '@nuxtjs/style-resources',
    ],

    styleResources: {
        scss: [
            '@/assets/scss/helpers/*.scss'
        ]
    }
}
```

3) Might need to restart your local Nuxt dev server.
