### ISSUE TITLE
production ready (with now)

### ISSUE THREAD

**Issue by tchret** [anteriovieira/nuxt-sass-resources-loader#2]
Hi @anteriovieira, 

Thank you for the plugin, really useful for me in dev mode.
Unfortunately I can't get it works in production. (I'm trying to deploy the website with `now`)

![image](https://user-images.githubusercontent.com/4539476/34343250-c5c0b4e2-e9c8-11e7-948b-d6788f87f257.png)

Do you have a tips for me?

Cheers :)

**Comment by anteriovieira** [comment]
Hi @tchret , did you install the plugin in dev mode?

**Comment by tchret** [comment]
It works great now, thank you :)

**Comment by samrose3** [comment]
@tchret @anteriovieira I have the plugin in my project dependencies (not devDependencies) but am still getting this error :\ Any other thoughts?

**Error**
![now-error](https://user-images.githubusercontent.com/11774595/38481078-d8c00730-3b7d-11e8-829b-bbadeb3e543a.png)

**package.json**
![package-json](https://user-images.githubusercontent.com/11774595/38481079-d8f7d9c6-3b7d-11e8-9613-861e8b02b17e.png)

**Comment by anteriovieira** [comment]
Can I see how you implemented it in the nuxt.config.js file?
