### ISSUE TITLE
Package seems to be broken with nuxt 2.4.0

### ISSUE THREAD

**Issue by LeCoupa** [anteriovieira/nuxt-sass-resources-loader#25]
When updating to `nuxt@2.4.0`, the package does not work. https://github.com/nuxt/nuxt.js/issues/4869#issuecomment-458276540

Here is my configuration:

```javascript
module.exports = {
  modules: [
    "@nuxtjs/axios",
    "@nuxtjs/dotenv",
    "@nuxtjs/pwa",
    "nuxt-material-design-icons",
    [
      "nuxt-sass-resources-loader",
      [
        // Global variables, site-wide settings, config switches, etc
        "@/assets/settings/_settings.colors.scss",

        // Site-wide mixins and functions
        "@/assets/tools/_tools.mq.scss"
      ]
  ]
}
```

**Compilation Errors**:

```bash
 ERROR  Failed to compile with 20 errors                                                                                                  friendly-errors 20:54:35

ERROR  in ./pages/settings/experiments/editor/_id.vue?vue&type=style&index=0&lang=scss&                                                  friendly-errors 20:54:35

Module build failed (from ./node_modules/sass-loader/lib/loader.js):                                                                      friendly-errors 20:54:35

color: $nepal;
```

**Comment by TheAlexLichter** [comment]
Small remark: There is an nuxt-community package for loading SASS/LESS/Stylus variables for some time

https://github.com/nuxt-community/style-resources-module

That one should also work with the current version :relaxed:

**Comment by anteriovieira** [comment]
Thanks @manniL 

> :warning: We are closing the support for this package and transferred to the official community package. So we strongly suggest that you use the official community package [@nuxtjs/style-resources](https://github.com/nuxt-community/style-resources-module).

**Comment by TheAlexLichter** [comment]
@anteriovieira Thanks for the outstanding work :heart:

**Comment by LeCoupa** [comment]
Thanks @anteriovieira 🥇. I just made the changes yesterday night. I guess we can close the issue. 👍
