### ISSUE TITLE
Update readme?

### ISSUE THREAD

**Issue by jordanboston** [anteriovieira/nuxt-sass-resources-loader#5]
Can you update the readme with a note about using this:
```javascript
const resolve = require('path').resolve
```
...instead of this?  _(in some cases)_
```javascript
import {resolve} from 'path'
```

I'm using nuxt 1.0.0-rc11 & nuxt-sass-resources-loader 1.1.1  but it only works for me using the first const and not the import for some reason.  This really threw me off and I almost did not bother trying to get it working, but then found a note about that in previous issues.

Works great though!  Nice work on this, thanks.

**Comment by anteriovieira** [comment]
Hi @jordanboston I would be happy if you could send me a pull request with this note :smiley:

**Comment by jordanboston** [comment]
Ok, will do.  Thanks
