### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by davision** [anteriovieira/nuxt-sass-resources-loader#7]
I'm trying to integrate your plugin for quite a while but didn't get lucky so far. I'm getting this error from multiple .vue components:

```
Module build failed: Error:
      Can't find sass resources in your config.
      Make sure loader.options.resources exists.

    at Object.module.exports (/node_modules/sass-resources-loader/lib/loader.js:55:17)
```

I tried all possible combinations of including scss resources:
```
  resolve(__dirname, "assets/css/config/_variables.scss")
  resolve(__dirname, "/assets/css/config/_variables.scss")
  resolve(__dirname, "./assets/css/config/_variables.scss")
```

Do you have an idea, what am I doing wrong?

**Comment by anteriovieira** [comment]
Can you show me your nuxt.config.js file?

**Comment by davision** [comment]
Sure, here it is:

`
const meta = {
  title: '',
  description: '',
  image: '',
  image_wide: ''
}

const resolve = require("path").resolve;

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: meta.title,
    meta: [
      { property: "og:url", content: "" },
      { property: "og:title", content: meta.title },
      { property: "og:description", content: meta.description },
      { property: "og:image", content: meta.image },
      { property: "og:image:type", content: "image/png" },
      { property: "og:image:width", content: "400" },
      { property: "og:image:height", content: "400" },

      { property: "twitter:card", content: "summary_large_image" },
      { property: "twitter:site", content: "" },
      { property: "twitter:creator", content: "" },
      { property: "twitter:title", content: meta.title },
      { property: "twitter:description", content: meta.description },
      { property: "twitter:image", content: meta.image_wide },

      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: meta.description }
    ],
    link: [{ rel: "icon", type: "image/png", href: "/favicon.png" }]
  },
  css: [
    { src: "~/assets/css/animations.scss" },
    { src: "~/assets/css/styles.scss" }
  ],
  loading: {
    color: "#0DCAF2"
  },
  plugins: [{ src: "~plugins/ga.js", ssr: false }],
  modules: [
    [
      "nuxt-sass-resources-loader",
      [
        resolve(__dirname, "~foundation-sites/scss/foundation"),
        resolve(__dirname, "assets/css/config/_variables.scss")
      ]
    ]
  ],
  build: {
    /*
    ** Run ESLint on save
    */
    extend(config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/
        });
      }

      const urlLoader = config.module.rules.find(
        rule => rule.loader === "url-loader"
      );
      urlLoader.test = /\.(png|jpe?g|gif)$/;

      config.module.rules.push({
        test: /\.svg$/,
        loader: "vue-svg-loader",
        exclude: /node_modules/
      });
    }
  }
};
`

**Comment by javimosch** [comment]
Double check the file path. 
Try path.join(process.cwd(),'relative/path') inestead

**Comment by anteriovieira** [comment]
Hi @davision install version v1.2.0 and try :

```js
...
  modules: [
    [
      "nuxt-sass-resources-loader",
      [
        "foundation-sites/scss/foundation", // to components
        "@/assets/css/config/_variables.scss" // to files
      ]
    ]
  ],
...
```

**Comment by davision** [comment]
Thank you for your reply. It looks like import now works, but I'm getting weird errors form imported scss files:

```
 Error: /Users/davidlicen/Documents/Projects/oceanpool/www/assets/css/config/_variables.scss:1
  (function (exports, require, module, __filename, __dirname) { $white: #fff;
                                                                        ^
  SyntaxError: Invalid or unexpected token

```

**Comment by anteriovieira** [comment]
> Does this plugin work only for .sass files?

It works with sass and scss 

----

>  Also forgot to mention that path "foundation-sites/scss/foundation" should pointing to node_modules folder. 

Ok, in the version `v1.2.0`  this should work.
```js
  modules: [
    [
      "nuxt-sass-resources-loader",
      [
       // foundation-sites component in node_modules
        "foundation-sites/scss/foundation.scss"
      ]
    ]
  ],
```

**Comment by anteriovieira** [comment]
@davision what is the nuxt version?

**Comment by davision** [comment]
I am using the latest 1.4. It's really annoying. If I run `npm run dev` I am first getting:
```
  Error: /node_modules/foundation-sites/scss/foundation.scss:9
  @import '../_vendor/normalize-scss/sass/normalize';
  ^
  SyntaxError: Invalid or unexpected token
```

and then from each vue file:

```
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.5.13

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

**Comment by davision** [comment]
The issue with vue-tempalte-compiler was not related to this module. I've fixed that, but still I'm getting this from every .vue file:

```
Module build failed: Error:
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.

    at Object.module.exports (/node_modules/sass-resources-loader/lib/loader.js:73:18)
```

**Comment by davision** [comment]
This is whole output: 

```
Module build failed: Error:
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.

    at Object.module.exports (/node_modules/sass-resources-loader/lib/loader.js:73:18)

 @ ./node_modules/vue-style-loader?{"sourceMap":true}!./node_modules/css-loader?{"sourceMap":true,"minimize":false,"importLoaders":1,"alias":{"/assets":"/assets","/static":"/static"}}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-ab28c9fc","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/sass-resources-loader/lib/loader.js?{"resources":[]}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./components/Howitworks.vue 4:14-635 13:3-17:5 14:22-643
 @ ./components/Howitworks.vue
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

**Comment by anteriovieira** [comment]
This is probably an error in how to pass the parameters, try using the sassResources option:

```js
module.exports = {
  modules: [
    'nuxt-sass-resources-loader'
  ],
  sassResources: [
    'foundation-sites/scss/foundation.scss'
  ]
}
```

**Comment by davision** [comment]
Now we're talking! This finally works! Thank you very mush!

**Comment by anteriovieira** [comment]
Great! :smile:

**Comment by impulsivetomato** [comment]
@anteriovieira this solved my problem, thanks!

**Comment by david-mark** [comment]
Getting this in a Nuxt project every time. Doesn't matter whether the "sassResources" option is used or if the "resources" are pushed in an array. BTW, which is preferred at this time?

Module build failed: Error:
[1] Something wrong with provided resources.
[1] Make sure 'options.resources' is String or Array of Strings.

The thing is obviously confused and unable to express the cause of its confusion.
